In [66]:
import tensorflow as tf
from tensorflow import keras
import torch
import numpy as np
import tensorflow.keras.backend as K

In [62]:
random_zeros = np.zeros((32, 30))
one_index = np.random.randint(0, 30, 32)
for x in range(len(random_zeros)):
    random_zeros[x][one_index[x]] = 1
targets = random_zeros
inputs = np.random.random((32, 30))

In [18]:
prec = keras.metrics.Precision()

In [21]:
prec(targets, inputs).numpy()

0.04453441

In [29]:
temp_index = np.argmax(inputs, axis = 1)

In [28]:
t = np.zeros((32, 30))

In [30]:
for x in range(len(t)):
    t[x][temp_index[x]] = 1

In [39]:
tp = np.sum(np.logical_and(t == 1, targets == 1))
fp = np.sum(np.logical_and(t == 0, targets == 1))

In [52]:
a = np.argmax(inputs, axis = 1)
b = np.argmax(targets, axis = 1)

In [57]:
tp = np.sum(a == b)
fp = 

In [60]:
np.sum(a != b)

32

In [129]:
random_zeros = np.zeros((32, 30))
one_index = np.random.randint(0, 30, 32)
for x in range(len(random_zeros)):
    random_zeros[x][one_index[x]] = 1
targets = random_zeros
inputs = np.random.random((32, 30))

In [164]:
def calculate_prec(inputs, targets):
    pass
    # inputs = tf.argmax(inputs, axis=1)
    # targets = tf.argmax(targets, axis=1)
    # temp = K.equal(inputs, targets)
    # temp = K.cast(temp, tf.int32)
    # temp = tf.reduce_sum(temp)
    # print(temp)
    # temp = tf.unique_with_counts(temp)
    # print(temp)
    # print(temp)
    # tp = temp[2][1]
    # fp = temp[2][0]
    # precision = tp / (tp + fp)
    # print(precision)
    # tf.unique_with_counts(tf.cast(K.equal(inputs, targets), tf.float32))
    # tp = K.sum(inputs == targets)
    # fp = K.sum(inputs != targets)
    # return tp / (tp + fp)
    # print(inputs, targets)

In [165]:
# calculate_prec(tf.convert_to_tensor(inputs), tf.convert_to_tensor(targets))

In [167]:
prec = keras.metrics.Precision()
prec(targets, inputs)

<tf.Tensor: shape=(), dtype=float32, numpy=0.03862661>

In [176]:
print(np.sum((np.argmax(inputs, axis = 1) == np.argmax(targets, axis = 1))))
print(np.sum((np.argmax(inputs, axis = 1) != np.argmax(targets, axis = 1))))

0
32


In [338]:
random_zeros = np.zeros((32, 30))
one_index = np.random.randint(0, 30, 32)
for x in range(len(random_zeros)):
    random_zeros[x][one_index[x]] = 1
targets = random_zeros
inputs = np.random.random((32, 30))

In [311]:
input_maxed = np.argmax(inputs, axis = 1)
target_maxed = np.argmax(targets, axis = 1)

In [312]:
tf_zeros = tf.zeros((32, 30))
u_indexes = tf.stack([tf.range(random_zeros.shape[0]), inputs_maxed], axis = 1)
ones = tf.ones(random_zeros.shape[0])
zeros = tf.zeros((random_zeros.shape[0], random_zeros.shape[1]))
inputs = tf.tensor_scatter_nd_update(zeros, u_indexes, ones)

In [315]:
targets = tf.constant(targets)

In [319]:
(tf.logical_and(targets == 1, inputs == 1))

<tf.Tensor: shape=(32, 30), dtype=bool, numpy=
array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        Fal

In [327]:
x, y = np.array([1, 0, 0]), np.array([1, 0, 0])

In [330]:
tf.math.reduce_sum(tf.cast(tf.logical_and(x == 0, y == 0), tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [344]:
TP = K.sum(K.round(K.clip((inputs * targets), 0, 1)))
positives = 

<tf.Tensor: shape=(), dtype=float64, numpy=18.0>

In [ ]:
# K.round(K.clip((inputs * targets), 0, 1))

In [349]:
K.sum(inputs*targets)

<tf.Tensor: shape=(), dtype=float64, numpy=17.40131389468559>

In [350]:
K.sum(K.round(inputs*targets))

<tf.Tensor: shape=(), dtype=float64, numpy=18.0>

In [205]:
# Macro precision evaluation calculation
# Tensorflow implementation
def macro_precision():
    # For 2 class
    # class 1: calculate tp
    # class 2: calculate fp
    K.round(K.clip())